"use client";

import { useEffect, useRef, useState, type DragEvent, type FormEvent, type WheelEvent } from "react";
import { saveProcess } from "./actions";

type ProcessStep = { step_type: string; description: string | null; duration_minutes: number | null; temperature_f: number | null };
type BakingStage = { temperature_f: number | null; duration_minutes: number | null; lid_on: boolean | null; description: string | null };
type SaveState = "saved" | "saving" | "unsaved" | "error";
const defaultSteps: ProcessStep[] = [{ step_type: "mixing", description: "", duration_minutes: null, temperature_f: null },{ step_type: "kneading", description: "", duration_minutes: null, temperature_f: null },{ step_type: "proofing", description: "First proof", duration_minutes: null, temperature_f: null },{ step_type: "shaping", description: "", duration_minutes: null, temperature_f: null },{ step_type: "proofing", description: "Final proof", duration_minutes: null, temperature_f: null }];
const defaultBaking: BakingStage[] = [{ temperature_f: 450, duration_minutes: null, lid_on: true, description: "" }, { temperature_f: 450, duration_minutes: null, lid_on: false, description: "" }];
const coolingNames = ["Cooling in Dutch oven", "Cooling on rack"];
function preventWheelChange(e: WheelEvent<HTMLInputElement>) { e.currentTarget.blur(); }

export default function ProcessForm({ bakeId, initialSteps, initialBaking, initialCooling }: { bakeId: string; initialSteps: ProcessStep[]; initialBaking: BakingStage[]; initialCooling: ProcessStep[] }) {
  const [steps, setSteps] = useState(initialSteps.length ? initialSteps : defaultSteps); const [baking, setBaking] = useState(initialBaking.length ? initialBaking : defaultBaking);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null); const [saveState, setSaveState] = useState<SaveState>("saved"); const [saveError, setSaveError] = useState("");
  const [openSection, setOpenSection] = useState<"process" | "baking" | "cooling">(initialCooling.some((s) => s.duration_minutes !== null) ? "cooling" : initialBaking.some((s) => s.duration_minutes !== null) ? "baking" : "process");
  const formRef = useRef<HTMLFormElement>(null); const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null); const firstRender = useRef(true);
  const cooling = coolingNames.map((name) => initialCooling.find((s) => s.description === name) ?? { step_type: "resting", description: name, duration_minutes: null, temperature_f: null });
  async function saveNow() { if (!formRef.current) return; if (timerRef.current) clearTimeout(timerRef.current); setSaveState("saving"); setSaveError(""); const r = await saveProcess(bakeId, new FormData(formRef.current)); if (r.ok) setSaveState("saved"); else { setSaveState("error"); setSaveError(r.error ?? "Could not save."); } }
  function scheduleSave() { setSaveState("unsaved"); if (timerRef.current) clearTimeout(timerRef.current); timerRef.current = setTimeout(saveNow, 900); }
  useEffect(() => { if (firstRender.current) { firstRender.current = false; return; } scheduleSave(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [steps, baking]);
  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);
  function handleChange(e: FormEvent<HTMLFormElement>) { const t = e.target as HTMLInputElement | HTMLSelectElement; if (t.name) scheduleSave(); }
  function addStep() { setSteps((c) => [...c, { step_type: "other", description: "", duration_minutes: null, temperature_f: null }]); } function deleteStep(i: number) { setSteps((c) => c.filter((_, x) => x !== i)); }
  function moveStep(from: number, to: number) { if (to < 0 || to >= steps.length || from === to) return; setSteps((c) => { const n = [...c]; const [m] = n.splice(from, 1); n.splice(to, 0, m); return n; }); }
  function dropStep(e: DragEvent<HTMLDivElement>, i: number) { e.preventDefault(); if (draggedIndex !== null) moveStep(draggedIndex, i); setDraggedIndex(null); }
  function addBakingStage() { setBaking((c) => [...c, { temperature_f: 450, duration_minutes: null, lid_on: false, description: "" }]); } function deleteBakingStage(i: number) { setBaking((c) => c.filter((_, x) => x !== i)); }
  const header = (title: string, subtitle: string, section: "process" | "baking" | "cooling") => <button type="button" onClick={() => setOpenSection(section)} className="flex w-full items-center justify-between p-5 text-left"><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-stone-500">{subtitle}</p></div><span className="text-xl text-stone-400">{openSection === section ? "−" : "+"}</span></button>;

  return <form ref={formRef} onChange={handleChange} className="space-y-4">
    <div className="sticky top-3 z-10 flex justify-end pointer-events-none"><div className={`rounded-full border bg-white/95 px-3 py-1.5 text-xs font-semibold shadow-sm ${saveState === "error" ? "border-red-200 text-red-700" : "border-stone-200 text-stone-600"}`}>{saveState === "saving" ? "Saving…" : saveState === "unsaved" ? "Changes pending…" : saveState === "error" ? `Not saved: ${saveError}` : "✓ Saved"}</div></div>

    <section className="overflow-visible rounded-3xl border border-stone-200 bg-white shadow-sm">{header("Process", openSection === "process" ? "Drag steps or use the arrows to put them in order." : `${steps.length} process steps`, "process")}{openSection === "process" ? <div className="border-t border-stone-100 p-5"><div className="space-y-4">{steps.map((step, i) => <div key={i} draggable onDragStart={() => setDraggedIndex(i)} onDragOver={(e) => e.preventDefault()} onDrop={(e) => dropStep(e, i)} className="rounded-2xl bg-stone-50 p-4"><div className="mb-3 flex items-center justify-between"><span className="cursor-grab text-sm font-semibold text-stone-500">☰ Step {i + 1}</span><div className="flex gap-2"><button type="button" onClick={() => moveStep(i,i-1)} disabled={i===0} className="min-h-9 min-w-10 rounded-lg border bg-white disabled:opacity-30">↑</button><button type="button" onClick={() => moveStep(i,i+1)} disabled={i===steps.length-1} className="min-h-9 min-w-10 rounded-lg border bg-white disabled:opacity-30">↓</button><button type="button" onClick={() => deleteStep(i)} className="flex h-9 w-9 items-center justify-center rounded-full border bg-white">−</button></div></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Step<select name="step_type" defaultValue={step.step_type} className="mt-2 min-h-12 w-full rounded-xl border bg-white px-3"><option value="mixing">Mixing</option><option value="kneading">Kneading</option><option value="proofing">Proofing</option><option value="shaping">Shaping</option><option value="resting">Resting</option><option value="other">Other</option></select></label><label className="text-sm font-medium">Minutes<input name="step_duration" type="number" min="0" defaultValue={step.duration_minutes ?? ""} onWheel={preventWheelChange} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label></div><label className="mt-3 block text-sm font-medium">What did you do?<input name="step_description" defaultValue={step.description ?? ""} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label><label className="mt-3 block text-sm font-medium">Temperature °F <span className="font-normal text-stone-400">(when useful)</span><input name="step_temperature" type="number" step="0.1" defaultValue={step.temperature_f ?? ""} onWheel={preventWheelChange} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label></div>)}</div><button type="button" onClick={addStep} className="mt-4 min-h-12 w-full rounded-xl border border-dashed px-4 font-semibold">+ Add another process step</button><button type="button" onClick={() => setOpenSection("baking")} className="mt-4 min-h-12 w-full rounded-xl bg-stone-900 px-4 font-semibold text-white">Move on to Baking →</button></div> : null}</section>

    <section className="rounded-3xl border border-stone-200 bg-white shadow-sm">{header("Baking", openSection === "baking" ? "Record each oven stage." : `${baking.length} baking stages`, "baking")}{openSection === "baking" ? <div className="border-t p-5"><div className="space-y-4">{baking.map((stage,i) => <div key={i} className="rounded-2xl bg-stone-50 p-4"><div className="flex justify-end"><button type="button" onClick={() => deleteBakingStage(i)} className="flex h-9 w-9 items-center justify-center rounded-full border bg-white">−</button></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Oven °F<input name="bake_temperature" type="number" defaultValue={stage.temperature_f ?? ""} onWheel={preventWheelChange} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label><label className="text-sm font-medium">Minutes<input name="bake_duration" type="number" defaultValue={stage.duration_minutes ?? ""} onWheel={preventWheelChange} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label></div><div className="mt-3 grid grid-cols-[9rem_1fr] gap-3"><label className="text-sm font-medium">Lid<select name="bake_lid" defaultValue={stage.lid_on ? "on" : "off"} className="mt-2 min-h-12 w-full rounded-xl border bg-white px-3"><option value="on">On</option><option value="off">Off</option></select></label><label className="text-sm font-medium">Note<input name="bake_description" defaultValue={stage.description ?? ""} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label></div></div>)}</div><button type="button" onClick={addBakingStage} className="mt-4 min-h-12 w-full rounded-xl border border-dashed font-semibold">+ Add baking stage</button><button type="button" onClick={() => setOpenSection("cooling")} className="mt-4 min-h-12 w-full rounded-xl bg-stone-900 font-semibold text-white">Move on to Cooling →</button></div> : null}</section>

    <section className="rounded-3xl border border-stone-200 bg-white shadow-sm">{header("Cooling", openSection === "cooling" ? "Record cooling after the loaf leaves the oven." : "Cooling details", "cooling")}{openSection === "cooling" ? <div className="border-t p-5"><div className="space-y-4">{cooling.map((step) => <div key={step.description} className="rounded-2xl bg-stone-50 p-4"><input type="hidden" name="cooling_name" value={step.description ?? ""}/><h3 className="font-semibold">{step.description}</h3><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-medium">Minutes<input name="cooling_duration" type="number" defaultValue={step.duration_minutes ?? ""} onWheel={preventWheelChange} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label><label className="text-sm font-medium">Temperature °F<input name="cooling_temperature" type="number" defaultValue={step.temperature_f ?? ""} onWheel={preventWheelChange} className="mt-2 min-h-12 w-full rounded-xl border px-3" /></label></div></div>)}</div><p className="mt-4 text-sm text-stone-500">When you're ready to evaluate the loaf, scroll to Evaluation below. Process and Baking stay collapsed unless you reopen them.</p></div> : null}</section>
  </form>;
}
